"""added email column

Revision ID: 25fc4d0c1c01
Revises: 20a15b243df3
Create Date: 2026-07-22 16:32:03.093707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25fc4d0c1c01'
down_revision: Union[str, Sequence[str], None] = '20a15b243df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'tickets', ['id'])
    op.create_unique_constraint(None, 'tickets', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='unique')
    op.drop_constraint(None, 'tickets', type_='unique')
    op.drop_column('tickets', 'email')
    # ### end Alembic commands ###
